[package]
name = "imgui-gfx-hal"
version = "0.1.0"
authors = ["Benjamin <benjamin.fik.lee@gmail.com>"]

[dependencies]
gfx-hal = { git = "https://github.com/gfx-rs/gfx", rev = "6cb2a800b" }
imgui = { git = "https://github.com/Gekkio/imgui-rs" }
failure = "0.1.1"
gfx-memory = { git = "https://github.com/gfx-rs/gfx-memory" }
memoffset = "0.2.1"

[dev-dependencies]
gfx-backend-vulkan = { git = "https://github.com/gfx-rs/gfx", rev = "6cb2a800b" }
env_logger = "0.5.10"
winit = "0.15"
