[package]
name = "imgui-gfx-hal"
version = "0.1.0"
authors = ["Benjamin <benjamin.fik.lee@gmail.com>"]

[dependencies]
failure = "0.1"
memoffset = "0.2"
gfx-hal = "~0.1.0"
imgui = "~0.0.20"

[dev-dependencies]
gfx-backend-vulkan = "0.1.0"
env_logger = "0.6"
winit = "0.18"
